function dummy=plot_channel_flags(my_date)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Show flags raised in fp_data using get_array_info(my_date).
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Look at mid-2011 if no other date is specified.
if nargin<1
    my_date=20110801;
end

[p,~]=get_array_info(my_date);

% Separate the channel flags into binary components.
bit_flags=false(length(p.gcp),21);
p.flag(isnan(p.flag))=0;
for jj=1:21,
    bit_flags(:,jj)=logical(bitget(p.flag,jj));
end

% Plot black on white for each rx.
for jj=1:(length(p.gcp)/528)
    figure(jj)
    imagesc(~bit_flags((528*jj-527):528*jj,:)')
    colormap(gray)
    %title('bicep2\_20100105')
    title(['rx',int2str(jj-1)])
    set(gca,'TickLength',[0 0])
    grid on
    set(gca,'XTick',1:33:528)
    set(gca,'XTickLabel',(0:33:527)')
    set(gca,'YTick',1:21)
    set(gca,'YTickLabel',{...
        'open',...
        'noisy TES',...
        'noisy SQ amp',...
        'other',...
        'other2',...
        'epsilon',...
        'worst tau',...
        'changed tau',...
        'TES broken',...
        'TES open',...
        'TES not bonded',...
        'antenna short',...
        'dark squid',...
        'dead SQ1',...
        'dead SQ2',...
        'dead SSA',...
        'bad TES',...
        'TES off transition',...
        'Antenna broken',...
        'multiple SQ1s',...
        'bad beams'
        })
end

dummy=true;